import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import BookProvider from "./context/BookContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BookProvider>
          <div className="lg:flex">
            <Header />
            <main className="flex-1 lg:ml-[200px] mt-16 lg:mt-0">
              {children}
              <ToastContainer />
            </main>
          </div>
        </BookProvider>
      </body>
    </html>
  );
}
